### ISSUE TITLE
We're not sending emails, the last email sent was on 13 April

### ISSUE THREAD

**Issue by pranav7** [pranav7/cadet-app#149]
https://account.postmarkapp.com/servers/3328147/streams/outbound/events

![image](https://user-images.githubusercontent.com/1835120/116449236-963bad00-a877-11eb-9a47-59b7febc9c40.png)

**Comment by ruthwickp** [comment]
Did some digging and saw this error in the sidekiq logs

```
2021-04-28T17:57:08.299Z 12969 TID-133zqw ActionMailer::DeliveryJob JID-a7af64bd6449e6af8b644fb9 INFO: start
2021-04-28T17:57:08.348Z 12969 TID-133zqw ActionMailer::DeliveryJob JID-a7af64bd6449e6af8b644fb9 INFO: fail: 0.05 sec
2021-04-28T17:57:08.349Z 12969 TID-133zqw WARN: {"context":"Job raised exception","job":{"class":"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper","wrapped":"ActionMailer::DeliveryJob","queue":"mailers","args":[{"job_class":"ActionMailer::DeliveryJob","job_id":"87cd247d-e2fd-4763-a27e-7ca5aa741a34","provider_job_id":null,"queue_name":"mailers","priority":null,"arguments":["PostNotificationMailer","new_post","deliver_now",{"_aj_globalid":"gid://cadet-app/Post/2032"},{"_aj_globalid":"gid://cadet-app/User/1056"}],"executions":0,"locale":"en"}],"retry":true,"jid":"a7af64bd6449e6af8b644fb9","created_at":1619605911.6331403,"enqueued_at":1619632628.2984748,"error_message":"SSL_connect SYSCALL returned=5 errno=0 state=unknown state","error_class":"OpenSSL::SSL::SSLError","failed_at":1619605911.748604,"retry_count":10,"retried_at":1619622333.3825288},"jobstr":"{\"class\":\"ActiveJob::QueueAdapters::SidekiqAdapter::JobWrapper\",\"wrapped\":\"ActionMailer::DeliveryJob\",\"queue\":\"mailers\",\"args\":[{\"job_class\":\"ActionMailer::DeliveryJob\",\"job_id\":\"87cd247d-e2fd-4763-a27e-7ca5aa741a34\",\"provider_job_id\":null,\"queue_name\":\"mailers\",\"priority\":null,\"arguments\":[\"PostNotificationMailer\",\"new_post\",\"deliver_now\",{\"_aj_globalid\":\"gid://cadet-app/Post/2032\"},{\"_aj_globalid\":\"gid://cadet-app/User/1056\"}],\"executions\":0,\"locale\":\"en\"}],\"retry\":true,\"jid\":\"a7af64bd6449e6af8b644fb9\",\"created_at\":1619605911.6331403,\"enqueued_at\":1619632628.2984748,\"error_message\":\"SSL_connect SYSCALL returned=5 errno=0 state=unknown state\",\"error_class\":\"OpenSSL::SSL::SSLError\",\"failed_at\":1619605911.748604,\"retry_count\":10,\"retried_at\":1619622333.3825288}"}
2021-04-28T17:57:08.349Z 12969 TID-133zqw WARN: OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=unknown state
2021-04-28T17:57:08.349Z 12969 TID-133zqw WARN: /home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:948:in `connect'
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:876:in `start'
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1407:in `request'
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1430:in `send_entity'
/home/rails/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/net/http.rb:1218:in `post'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/postmark-1.10.0/lib/postmark/http_client.rb:30:in `block in post'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/postmark-1.10.0/lib/postmark/http_client.rb:93:in `block in do_request'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/postmark-1.10.0/lib/postmark/http_client.rb:92:in `synchronize'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/postmark-1.10.0/lib/postmark/http_client.rb:92:in `do_request'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/postmark-1.10.0/lib/postmark/http_client.rb:30:in `post'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/postmark-1.10.0/lib/postmark/api_client.rb:33:in `block (2 levels) in deliver_message'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/postmark-1.10.0/lib/postmark/client.rb:54:in `take_response_of'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/postmark-1.10.0/lib/postmark/api_client.rb:33:in `block in deliver_message'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/postmark-1.10.0/lib/postmark/client.rb:39:in `with_retries'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/postmark-1.10.0/lib/postmark/api_client.rb:32:in `deliver_message'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/postmark-1.10.0/lib/postmark/handlers/mail.rb:14:in `deliver!'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
/home/rails/apps/cadet-app/shared/bundle/ruby/2.4.0/gems/actionmailer-5.2.4.4/lib/action_mailer/base.rb:560:in `block in deliver_mail'```

**Comment by ruthwickp** [comment]
This might be relevant: https://github.com/wildbit/postmark-gem/issues/102

**Comment by ruthwickp** [comment]
Fixed issue and emails are being sent out now.
