### ISSUE TITLE
master broken due to tailwind postcss issue

### ISSUE THREAD

**Issue by pranav7** [pranav7/cadet-app#168]
```
ERROR in ./app/javascript/stylesheets/application.scss (./node_modules/css-loader/dist/cjs.js??ref--6-1!./node_modules/postcss-loader/src??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./app/javascript/stylesheets/application.scss)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: PostCSS plugin tailwindcss requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (/Users/pranavsingh/Cadet/cadet-app/node_modules/postcss/lib/processor.js:153:15)
    at new Processor (/Users/pranavsingh/Cadet/cadet-app/node_modules/postcss/lib/processor.js:56:25)
    at postcss (/Users/pranavsingh/Cadet/cadet-app/node_modules/postcss/lib/postcss.js:55:10)
    at /Users/pranavsingh/Cadet/cadet-app/node_modules/postcss-loader/src/index.js:140:12
```

**Comment by pranav7** [comment]
Might be due to https://github.com/pranav7/cadet-app/pull/166, but I can't currently deploy `master`
